### ISSUE TITLE
Simplify SSL configuration

### ISSUE THREAD

**Issue by Hakky54** [GreenOpsInc/atlas#60]
Hi, hello!

I noticed your ssl configuration setup and I think it can be simplified which should result into less code!
I saw there is a fallback when the sslcontext is absent and at that point a custom sslcontext is being created while using a custom trustmanager which ignores the certificate validations. This option is built in in the SSLFactory which can be used.

The source code which I am referencing to is: https://github.com/GreenOpsInc/atlas/blob/26e375a549956a677b6189b6f44ed1178b6b2d20/util/src/main/java/com/greenops/util/httpclient/Builder.java#L52

Below is the existing code:
```java
public class Builder {

    public HttpClient build() throws Exception {
        if (this.sslCon == null) {
            SSLContext context = SSLContext.getInstance("TLS");
            context.init(null, trustAllCerts, new SecureRandom());
            this.builder.setSSLHostnameVerifier((s1, s2) -> true);
            return this.builder.setSSLContext(context).build();
        }
        return this.builder.setSSLContext(this.sslCon).build();
    }

    private static final TrustManager[] trustAllCerts = new TrustManager[]{
            new X509TrustManager() {
                public java.security.cert.X509Certificate[] getAcceptedIssuers() {
                    return null;
                }

                public void checkClientTrusted(
                        java.security.cert.X509Certificate[] certs, String authType) {
                }

                public void checkServerTrusted(
                        java.security.cert.X509Certificate[] certs, String authType) {
                }
            }
    };
}
```

And below is the refactored code which use the available hostname verifier and trustmanager which skips the validations:
```java
public class Builder {

    public HttpClient build() throws Exception {
        if (this.sslCon == null) {
            SSLFactory sslFactory = SSLFactory.builder()
                    .withUnsafeTrustMaterial()
                    .withUnsafeHostnameVerifier()
                    .build();
            this.builder.setSSLHostnameVerifier(sslFactory.getHostnameVerifier());
            return this.builder.setSSLContext(sslFactory.getSslContext()).build();
        }
        return this.builder.setSSLContext(this.sslCon).build();
    }

}
```

What do you think?

**Comment by mihirpandya-greenops** [comment]
Hi @Hakky54! This seems like a great option. Would you mind making a PR with the changes you suggested?

**Comment by Hakky54** [comment]
@mihirpandya-greenops Good suggestion, here you go: https://github.com/GreenOpsInc/atlas/pull/68

**Comment by mihirpandya-greenops** [comment]
Just merged it in @Hakky54, thanks for your help!
